### ISSUE TITLE
sbt hepek task causes scalafmt to fail with "org.scalafmt.sbt.ScalafmtSbtReporter$FailedToFormat: "

### ISSUE THREAD

**Issue by marracuene** [sake92/hepek-starter#4]
**UPDATE: TL;DR;**
This problem is caused by an issue in the sbt-scalafmt library (linked below).
Meantime if you have this problem you can fix it as follows:

Alter `build.sbt` as follows to directly pull in the scala-reflect library, taking care to set the version to the same as the `scalaVersion` defined at the top of the file.  In this example **2.13.1**.

```
scalaVersion in ThisBuild := "2.13.1"

...

lazy val root = (project in file("."))
  .settings(
    libraryDependencies ++= Seq(
     *"org.scala-lang" % "scala-reflect" % "2.13.1",
      "ba.sake" %% "hepek" % "0.7.0+7-434764e4-SNAPSHOT"
    ),

```
**=========== ORIGINAL ISSUE REPORT ===========**
Context: running on linux with the following versions:

```
cameron@mbc-lp-12:~$ uname -r
5.0.0-32-generic
```

```
cameron@mbc-lp-12:~/.workspace/blog$ java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

```
sbt:root> scalaBinaryVersion
[info] 2.13
```

```
cameron@mbc-lp-12:~/.workspace/blog$ /opt/sbt/bin/sbt --version
[INFO] [06/07/2020 11:07:19.946] [Thread-1] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
sbt script version: 1.3.4
```

I performed a fresh clone of `https://github.com/sake92/hepek-starter.git`, and when running hepek got a failure due to scalafmt as below.

```
cameron@mbc-lp-12:~/.workspace/blog$ /opt/sbt/bin/sbt
[info] Loading settings for project blog-build from metals.sbt,plugins.sbt ...
[info] Loading project definition from /home/cameron/.workspace/blog/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to root (in build file:/home/cameron/.workspace/blog/)
[info] sbt server started at local:///home/cameron/.sbt/1.0/server/35377b2a5bbdeec618c5/sock
sbt:root> 

sbt:root> hepek
[info] Formatting 4 Scala sources...
[error] stack trace is suppressed; run last Compile / scalafmt for the full output
[error] (Compile / scalafmt) org.scalafmt.sbt.ScalafmtSbtReporter$FailedToFormat: /home/cameron/.workspace/blog/.scalafmt.conf
[error] Total time: 1 s, completed Jun 7, 2020, 11:09:14 AM
```

As I am not that bothered about code formatting (I prefer to use the IDE's formatter), I disabled scalafmt in build.sbt as follows:
`scalafmtOnCompile in ThisBuild := false`

Re-running hepek, it now succeeds as below:
```
sbt:root> hepek
[info] Compiling 4 Scala sources to /home/cameron/.workspace/blog/target/scala-2.13/classes ...
[info] new client connected: network-1
https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.3.4/compiler-bridge_2.13-1.3.4.pom
  100.0% [##########] 2.8 KiB (1.7 KiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.pom
  100.0% [##########] 2.7 KiB (10.2 KiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.3.4/compiler-bridge_2.13-1.3.4-sources.jar
  100.0% [##########] 47.8 KiB (69.3 KiB / s)
[info] Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.1. Compiling...
8 warnings found
[info]   Compilation completed in 12.142s.
[success] Total time: 19 s, completed Jun 7, 2020, 11:19:40 AM
```

Testing the generated site with browsersync and a browser, shows that indeed the files were generated.  Altering the source code and rerunning hepek to regenerate the site, also works as expected.

**Comment by sake92** [comment]
Hello @marracuene and thanks for feedback! :)  
Seems like this is more of a Scalafmt issue, can you create an issue there maybe?  
Only thing that goes to mind is JDK 11, maybe that is an issue? 

Also can you run `last Compile / scalafmt` and post it? That should give us more details on error.

**Comment by marracuene** [comment]
Thanks for the quick reply.   Since  you had gone to such effort to create a simple and workable starter project I posted it here.    But if you think it is more appropriate to post it to Scalafmt and just mention it here, I can do that.   Please see the resolution I found, below, and advise how you would like to proceed.

Looking at the stack trace, it seems like the root cause is:
`[error] Caused by: java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator`

Looking at the dependencies which sbt has pulled in, I have scala-reflect-2.13.1 jar which contains scala.reflect.api.TypeCreator.  

The only recent-ish similar bug report I can find is this:
https://github.com/lihaoyi/PPrint/issues/24

Based on that I altered build.sbt as follows to directly pull in the scala-reflect library.    Exiting sbt, reentering, and running hepek again, the build now works.

```
lazy val root = (project in file("."))
  .settings(
    libraryDependencies ++= Seq(
      "org.scala-lang" % "scala-reflect" % "2.13.1",
      "ba.sake" %% "hepek" % "0.7.0+7-434764e4-SNAPSHOT"
    ),

```

Full original stack trace (before applying the resolution mentioned above):
```
sbt:root> last Compile / scalafmt
[debug] Change report:
[debug]         Checked: /home/cameron/.workspace/blog/src/main/scala/templates/Templates.scala, /home/cameron/.workspace/blog/src/main/scala/utils/Imports.scala, /home/cameron/.workspace/blog/src/main/scala/site/About.scala, /home/cameron/.workspace/blog/src/main/scala/site/Blog.scala, /home/cameron/.workspace/blog/src/main/scala/site/Index.scala
[debug]         Modified: /home/cameron/.workspace/blog/src/main/scala/templates/Templates.scala, /home/cameron/.workspace/blog/src/main/scala/utils/Imports.scala, /home/cameron/.workspace/blog/src/main/scala/site/About.scala, /home/cameron/.workspace/blog/src/main/scala/site/Blog.scala, /home/cameron/.workspace/blog/src/main/scala/site/Index.scala
[debug]         Unmodified: 
[debug]         Added: /home/cameron/.workspace/blog/src/main/scala/templates/Templates.scala, /home/cameron/.workspace/blog/src/main/scala/utils/Imports.scala, /home/cameron/.workspace/blog/src/main/scala/site/About.scala, /home/cameron/.workspace/blog/src/main/scala/site/Blog.scala, /home/cameron/.workspace/blog/src/main/scala/site/Index.scala
[debug]         Removed: 
[info] Formatting 5 Scala sources...
[debug] Adding repositories [https://repo1.maven.org/maven2/,file:////home/cameron/.sbt/preloaded/,https://oss.sonatype.org/content/repositories/snapshots]
[error] org.scalafmt.sbt.ScalafmtSbtReporter$FailedToFormat: /home/cameron/.workspace/blog/.scalafmt.conf
[error] Caused by: java.lang.reflect.InvocationTargetException
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at org.scalafmt.dynamic.utils.ReflectUtils$ClassReflectOps$.invokeStatic$extension(ReflectUtils.scala:34)
[error]         at org.scalafmt.dynamic.ScalafmtReflect.<init>(ScalafmtReflect.scala:31)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveClassPath$1(ScalafmtDynamic.scala:188)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveClassPath(ScalafmtDynamic.scala:186)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$3(ScalafmtDynamic.scala:177)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$1(ScalafmtDynamic.scala:177)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveFormatter(ScalafmtDynamic.scala:163)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfigWithScalafmt$2(ScalafmtDynamic.scala:142)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfigWithScalafmt(ScalafmtDynamic.scala:139)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfig$4(ScalafmtDynamic.scala:125)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:124)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.formatDetailed(ScalafmtDynamic.scala:108)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:70)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$withFormattedSources$2(ScalafmtPlugin.scala:122)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.withFormattedSources(ScalafmtPlugin.scala:116)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:164)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1(ScalafmtPlugin.scala:149)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1$adapted(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$4(ScalafmtPlugin.scala:269)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:298)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3(ScalafmtPlugin.scala:268)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3$adapted(ScalafmtPlugin.scala:263)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$1(ScalafmtPlugin.scala:272)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.trackSourcesAndConfig(ScalafmtPlugin.scala:274)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1(ScalafmtPlugin.scala:317)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1$adapted(ScalafmtPlugin.scala:310)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
[error]         at fansi.ColorCategory.$anonfun$Full$1(Fansi.scala:851)
[error]         at fansi.ColorCategory.$anonfun$Full$1$adapted(Fansi.scala:850)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:158)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at fansi.ColorCategory.<init>(Fansi.scala:850)
[error]         at fansi.Color$.<init>(Fansi.scala:717)
[error]         at fansi.Color$.<clinit>(Fansi.scala)
[error]         at fansi.Attr$.<init>(Fansi.scala:623)
[error]         at fansi.Attr$.<clinit>(Fansi.scala)
[error]         at fansi.Str$.<init>(Fansi.scala:373)
[error]         at fansi.Str$.<clinit>(Fansi.scala)
[error]         at org.scalafmt.config.OptIn$.$anonfun$surface$1(OptIn.scala:86)
[error]         at pprint.TPrint$$anon$2.render(TPrint.scala:21)
[error]         at org.scalafmt.config.OptIn$.surface$lzycompute(OptIn.scala:86)
[error]         at org.scalafmt.config.OptIn$.surface(OptIn.scala:86)
[error]         at org.scalafmt.config.OptIn.<init>(OptIn.scala:82)
[error]         at org.scalafmt.config.ScalafmtConfig$.apply$default$4(ScalafmtConfig.scala:131)
[error]         at org.scalafmt.config.ScalafmtConfig$.<init>(ScalafmtConfig.scala:208)
[error]         at org.scalafmt.config.ScalafmtConfig$.<clinit>(ScalafmtConfig.scala)
[error]         at org.scalafmt.Scalafmt$.format$default$2(Scalafmt.scala:87)
[error]         at org.scalafmt.Scalafmt.format$default$2(Scalafmt.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at org.scalafmt.dynamic.utils.ReflectUtils$ClassReflectOps$.invokeStatic$extension(ReflectUtils.scala:34)
[error]         at org.scalafmt.dynamic.ScalafmtReflect.<init>(ScalafmtReflect.scala:31)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveClassPath$1(ScalafmtDynamic.scala:188)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveClassPath(ScalafmtDynamic.scala:186)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$3(ScalafmtDynamic.scala:177)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$1(ScalafmtDynamic.scala:177)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveFormatter(ScalafmtDynamic.scala:163)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfigWithScalafmt$2(ScalafmtDynamic.scala:142)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfigWithScalafmt(ScalafmtDynamic.scala:139)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfig$4(ScalafmtDynamic.scala:125)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:124)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.formatDetailed(ScalafmtDynamic.scala:108)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:70)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$withFormattedSources$2(ScalafmtPlugin.scala:122)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.withFormattedSources(ScalafmtPlugin.scala:116)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:164)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1(ScalafmtPlugin.scala:149)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1$adapted(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$4(ScalafmtPlugin.scala:269)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:298)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3(ScalafmtPlugin.scala:268)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3$adapted(ScalafmtPlugin.scala:263)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$1(ScalafmtPlugin.scala:272)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.trackSourcesAndConfig(ScalafmtPlugin.scala:274)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1(ScalafmtPlugin.scala:317)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1$adapted(ScalafmtPlugin.scala:310)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.ClassNotFoundException: scala.reflect.api.TypeCreator
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error]         at fansi.ColorCategory.$anonfun$Full$1(Fansi.scala:851)
[error]         at fansi.ColorCategory.$anonfun$Full$1$adapted(Fansi.scala:850)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:158)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at fansi.ColorCategory.<init>(Fansi.scala:850)
[error]         at fansi.Color$.<init>(Fansi.scala:717)
[error]         at fansi.Color$.<clinit>(Fansi.scala)
[error]         at fansi.Attr$.<init>(Fansi.scala:623)
[error]         at fansi.Attr$.<clinit>(Fansi.scala)
[error]         at fansi.Str$.<init>(Fansi.scala:373)
[error]         at fansi.Str$.<clinit>(Fansi.scala)
[error]         at org.scalafmt.config.OptIn$.$anonfun$surface$1(OptIn.scala:86)
[error]         at pprint.TPrint$$anon$2.render(TPrint.scala:21)
[error]         at org.scalafmt.config.OptIn$.surface$lzycompute(OptIn.scala:86)
[error]         at org.scalafmt.config.OptIn$.surface(OptIn.scala:86)
[error]         at org.scalafmt.config.OptIn.<init>(OptIn.scala:82)
[error]         at org.scalafmt.config.ScalafmtConfig$.apply$default$4(ScalafmtConfig.scala:131)
[error]         at org.scalafmt.config.ScalafmtConfig$.<init>(ScalafmtConfig.scala:208)
[error]         at org.scalafmt.config.ScalafmtConfig$.<clinit>(ScalafmtConfig.scala)
[error]         at org.scalafmt.Scalafmt$.format$default$2(Scalafmt.scala:87)
[error]         at org.scalafmt.Scalafmt.format$default$2(Scalafmt.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at org.scalafmt.dynamic.utils.ReflectUtils$ClassReflectOps$.invokeStatic$extension(ReflectUtils.scala:34)
[error]         at org.scalafmt.dynamic.ScalafmtReflect.<init>(ScalafmtReflect.scala:31)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveClassPath$1(ScalafmtDynamic.scala:188)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveClassPath(ScalafmtDynamic.scala:186)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$3(ScalafmtDynamic.scala:177)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$1(ScalafmtDynamic.scala:177)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveFormatter(ScalafmtDynamic.scala:163)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfigWithScalafmt$2(ScalafmtDynamic.scala:142)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfigWithScalafmt(ScalafmtDynamic.scala:139)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfig$4(ScalafmtDynamic.scala:125)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:124)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.formatDetailed(ScalafmtDynamic.scala:108)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:70)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$withFormattedSources$2(ScalafmtPlugin.scala:122)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.withFormattedSources(ScalafmtPlugin.scala:116)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:164)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1(ScalafmtPlugin.scala:149)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1$adapted(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$4(ScalafmtPlugin.scala:269)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:298)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3(ScalafmtPlugin.scala:268)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3$adapted(ScalafmtPlugin.scala:263)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$1(ScalafmtPlugin.scala:272)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.trackSourcesAndConfig(ScalafmtPlugin.scala:274)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1(ScalafmtPlugin.scala:317)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1$adapted(ScalafmtPlugin.scala:310)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Compile / scalafmt) org.scalafmt.sbt.ScalafmtSbtReporter$FailedToFormat: /home/cameron/.workspace/blog/.scalafmt.conf
```

**Comment by marracuene** [comment]
Dedication!! Nice one.
